#!/usr/bin/env bash
# Create a symbolic link to this file in .git/hooks

GREEN=$'\e[1;32m'
RED=$'\e[0;31m'
CYAN=$'\e[1;34m'
GRAY=$'\e[1;33m'
NC=$'\e[0m'

mainline_wago=$(head -n 4 .github/workflows/upload2wago.sh | tail -n 1 | cut -d '=' -f 2)
mainline_patch=${mainline_wago//./0}
cata_wago=$(head -n 5 .github/workflows/upload2wago.sh | tail -n 1 | cut -d '=' -f 2)
cata_patch=${cata_wago//./0}


mainline_toc=$(head -n 1 EavesDrop_Mainline.toc | cut -d ' ' -f 3)
cata_toc=$(head -n 1 EavesDrop_Cata.toc | cut -d ' ' -f 3)

error=0

if [ "$mainline_patch" != "$mainline_toc" ]; then
    echo "Retail client Interface version is <$mainline_toc>"
    echo "which doesn't match with wago.io metadata: $mainline_wago ($mainline_patch)"
    echo "Check EavesDrop_Mainline.toc and .github/workflows/upload2wago.sh"
    echo
    error=1
fi

if [ "$cata_patch" != "$cata_toc" ]; then
    echo "CATA client Interface version is $cata_toc"
    echo "which doesn't match with wago.io metadata: $cata_wago"
    echo "Check EavesDrop_Cata.toc and .github/workflows/upload2wago.sh"
    echo
    error=1
fi

mainline_addon_version=$(head -n 4 EavesDrop_Mainline.toc | tail -n 1 | cut -d ' ' -f 3)
cata_addon_version=$(head -n 5 EavesDrop_Cata.toc | tail -n 1 | cut -d ' ' -f 3)

if [ "$mainline_addon_version" != "$cata_addon_version" ]; then
    echo "Addon version mismatch between CATA and Retail: $cata_addon_version <> $mainline_addon_version"
    echo
    error=1
fi

pat='(\s*--\s+@?(end-)?debug@?)|(\s*--\s*(end-)?debug@?)|(\s*\S+.*--@(end-)?debug@)|(\s*--@(end-)?debug[\s\S]+@)|(--@\s+(end-)?debug@)|(\s*--\s+@(end-)?debug@)|(--\s*@(end-)?debug(?:(((?!@).)+|\b)))$'
for file in $(git diff --name-only --cached); do
    if [[ $file != *.lua ]]; then
        echo -e "${GRAY}Skipping${NC} @debug@ sanity checks for$CYAN $file $NC"
        continue
    fi
    echo -e "Checking '@debug@' sanity checks for $CYAN$file $NC"
    if grep -qP "$pat" "$file"; then
        grep --color=always --with-filename -n -P "$pat" "$file"
        echo " "
        error=2
    fi
done

if [[ "$error" == 2 ]]; then
    echo -e "\033[0;31mThere is at least one typo with @debug@/@end-debug@"
fi
exit $error
